package my.test;
import java.io.*;

//Class to give more options to the admin
public class MoreOptions extends javax.swing.JFrame {
    BufferedReader in;
    PrintWriter out;
    /** Creates new form MoreOptions */
    public MoreOptions(BufferedReader in, PrintWriter out) {
        this.in = in;
        this.out = out;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addAdmin = new javax.swing.JButton();
        viewLogFiles = new javax.swing.JButton();
        viewActiveConnections = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addAdmin.setText("Add New Admin");
        addAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdminActionPerformed(evt);
            }
        });

        viewLogFiles.setText("View Log Files");
        viewLogFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLogFilesActionPerformed(evt);
            }
        });

        viewActiveConnections.setText("View Active Connections");
        viewActiveConnections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActiveConnectionsActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewLogFiles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewActiveConnections))
                    .addComponent(backButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAdmin)
                    .addComponent(viewActiveConnections)
                    .addComponent(viewLogFiles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(backButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//Go to Add Admin screen
private void addAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdminActionPerformed

    AddNewAdminScreen addAdmin = new AddNewAdminScreen(in, out);
    addAdmin.setLocation(this.getX(), this.getY());
    addAdmin.setVisible(true);
    this.setVisible(false);
}//GEN-LAST:event_addAdminActionPerformed

//Go back
private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

    testUI2 newScreen = new testUI2(in, out);
    newScreen.setLocation(this.getX(), this.getY());
    this.setVisible(false);
    newScreen.setVisible(true);
}//GEN-LAST:event_backButtonActionPerformed

//Go to the log screeen
private void viewLogFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLogFilesActionPerformed

    ViewLogFile logScreen = new ViewLogFile(in, out);
    logScreen.setLocation(this.getX(), this.getY());
    logScreen.setVisible(true);
    this.setVisible(false);
}//GEN-LAST:event_viewLogFilesActionPerformed

//Go to the active connections screen
private void viewActiveConnectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActiveConnectionsActionPerformed
    
    ActiveConnections connectionsScreen = new ActiveConnections(in, out);
    connectionsScreen.setLocation(this.getX(), this.getY());
    connectionsScreen.setVisible(true);
    this.setVisible(false);
}//GEN-LAST:event_viewActiveConnectionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoreOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoreOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoreOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoreOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MoreOptions(in, out).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAdmin;
    private javax.swing.JButton backButton;
    private javax.swing.JButton viewActiveConnections;
    private javax.swing.JButton viewLogFiles;
    // End of variables declaration//GEN-END:variables
}
