package my.test;

import java.io.*;
import java.text.DecimalFormat;
import javax.swing.*;

//Class to load test statistics to the admin
public class TestStatistics extends javax.swing.JFrame {
    private BufferedReader in;
    private PrintWriter out;
    private String nameOfTest;
    private DefaultListModel model = new DefaultListModel();
    private int lowScore;
    private int highScore;
    private int averageScore;
    private int lowScoreCount;
    private int highScoreCount;
    private int totalScore;
    /** Creates new form TestStatistics */
    public TestStatistics(BufferedReader in, PrintWriter out, String nameOfTest) {
        this.in = in;
        this.out = out;
        
        this.nameOfTest = nameOfTest;
        //Initialize components
        initComponents();

        //Declare formatter and all of the variables needed
        DecimalFormat format = new DecimalFormat("###.##");
        lowScore = 0;
        highScore = 0;
        averageScore = 0;
        lowScoreCount = 0;
        highScoreCount = 0;
        //Send command to the server
        out.println("LOAD_TEST_STATISTICS");
        out.flush();
        out.println(nameOfTest);
        out.flush();
        try{
            //Get the number of scores
            int numberOfScores = Integer.parseInt(in.readLine());
            String inLine;
            int temp;
            //Read in all teh scores
            for(int x = 0; x < numberOfScores; x++){
                //Format the scores
                inLine = format.format(Integer.parseInt(in.readLine()));
                //Add the score to the visual list
                model.addElement(inLine);
                //Condition statements to calculate low, high, and average
                temp = Integer.parseInt(inLine);
                totalScore += temp;
                if(x == 0){
                    highScore = temp;
                    lowScore = temp;
                }
                if(temp == lowScore){
                    lowScoreCount++;
                }
                if(temp < lowScore){
                    lowScore = temp;
                    lowScoreCount = 1;
                }
                if(temp == highScore){
                    highScoreCount++;
                }
                if(temp > highScore){
                    highScore = temp;
                    highScoreCount = 1;
                }
            }
            //Display stats if there are scores available
            if(numberOfScores != 0){
                averageScore = (totalScore/numberOfScores);
                lowScoreLabel.setText("Low Score = " + lowScore + " x " + lowScoreCount);
                highScoreLabel.setText("High Score = " + highScore + " x " + highScoreCount);
                averageScoreLabel.setText("Average Score = " + averageScore);
            }else{
                //Display nothing if there aren't any scores
                highScoreLabel.setText("There are no scores for this test!");
                lowScoreLabel.setText("");
                averageScoreLabel.setText("");
                model.addElement("No Scores!");
            }
        }catch(Exception e){
            //Handle the error
        }
        //Set the list with all the scores
        testNameLabel.setText(nameOfTest);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testNameLabel = new javax.swing.JLabel();
        highScoreLabel = new javax.swing.JLabel();
        lowScoreLabel = new javax.swing.JLabel();
        averageScoreLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scoresList = new javax.swing.JList(model);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        testNameLabel.setText("Test Name");

        highScoreLabel.setText("High Score = ");

        lowScoreLabel.setText("Low Score =");

        averageScoreLabel.setText("Average Score = ");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("All Scores:");

        jScrollPane1.setViewportView(scoresList);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(testNameLabel)
                        .add(178, 178, 178))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(backButton)
                            .add(lowScoreLabel)
                            .add(averageScoreLabel)
                            .add(highScoreLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 155, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(testNameLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(highScoreLabel)
                    .add(jLabel1))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(lowScoreLabel)
                        .add(18, 18, 18)
                        .add(averageScoreLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 159, Short.MAX_VALUE)
                        .add(backButton))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Button to go back
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        
        testUI2 newScreen = new testUI2(in, out);
        newScreen.setLocation(this.getX(), this.getY());
        this.setVisible(false);
        newScreen.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestStatistics(in, out, nameOfTest).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel averageScoreLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel highScoreLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lowScoreLabel;
    private javax.swing.JList scoresList;
    private javax.swing.JLabel testNameLabel;
    // End of variables declaration//GEN-END:variables

}
